# Generated by Django 6.0.5 on 2026-05-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0002_joke_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='slug',
            field=models.SlugField(default='Fix migrations', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
